//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EshopDAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EShoppyDBEntities : DbContext
    {
        public EShoppyDBEntities()
            : base("name=EShoppyDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Catogory> Catogories { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<ShoppingCart> ShoppingCarts { get; set; }

	//	public System.Data.Entity.DbSet<EshopMVC.Models.Category> Categories { get; set; }

		//public System.Data.Entity.DbSet<EshopMVC.Models.Category> Categories { get; set; }

		//public System.Data.Entity.DbSet<EshopMVC.Models.Category> Categories { get; set; }

		//public System.Data.Entity.DbSet<EshopMVC.Models.Category> Categories { get; set; }
	}
}
